---
wireguard_interface: "{{ lookup('env', 'WIREGUARD_INTERFACE') | default('wg0', true) }}"
wireguard_port: "{{ lookup('env', 'WIREGUARD_PORT') | default('51820', true) }}"
wireguard_address: "{{ lookup('env', 'WIREGUARD_ADDRESS') | default('10.200.0.1/24', true) }}"
wireguard_private_network: "{{ lookup('env', 'WIREGUARD_PRIVATE_NETWORK') | default('10.0.0.0/16', true) }}"
wireguard_peers: []
