- name: 👤 Ensure target user exists and in sudo group
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    state: present

- name: 🔓 Allow target user to use sudo without a password
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ deploy_user }}"
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    state: present
    owner: root
    group: root
    mode: '0440'
    validate: "visudo -cf %s"

- name: 🔑 Copy SSH public key to authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', ansible_user_public_key_file) }}"
