---
- name: Install k3s
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Enable k3s service
  ansible.builtin.systemd:
    name: k3s
    enabled: true
    state: started