all:
  vars:
    ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ops', true) }}"

  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
      vars:
        k8s_distro: microk8s

    vps:
      vars:
        k8s_distro: k3s
        ansible_user_public_key_file: "{{ lookup('env', 'PUB_KEY_PATH') }}"