all:
  vars:
    target_user: ops
    bootstrap: false

    ansible_become: true
    ansible_become_method: sudo

  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: "{{ lookup('env', 'USER') }}"
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
      vars:
        k8s_distro: microk8s

    vps:
      hosts:
        vps-1:
          ansible_host: "{{ lookup('env', 'VPS_IP_1') }}"
        vps-2:
          ansible_host: "{{ lookup('env', 'VPS_IP_2') }}"
        vps-3:
          ansible_host: "{{ lookup('env', 'VPS_IP_3') }}"
      vars:
        k8s_distro: k3s
        ansible_user: "{{ 'root' if bootstrap | bool else target_user }}"