---
- name: 🧩 K3s Cluster Setup
  hosts: k3s_cluster, local
  become: true
  tasks:
    - name: 📦 Install k3s
      ansible.builtin.import_role:
        name: prereq
      when: k8s_distro | default('k3s') == 'k3s'

    - name: 📦 Install k3s server
      ansible.builtin.import_role:
        name: k3s_server
      when: 
        - k8s_distro | default('k3s') == 'k3s'
        - inventory_hostname in groups['server']

    - name: 📦 Install k3s agent
      ansible.builtin.import_role:
        name: k3s_agent
      when: 
        - k8s_distro | default('k3s') == 'k3s'
        - inventory_hostname in groups['agent']
