---
- name: 🛠️ Platform foundation
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: 🏗️ Initialize System
      ansible.builtin.include_role:
        name: bootstrap

    - name: ⚙️ Deploy Cluster Role
      ansible.builtin.include_role:
        name: cluster