- name: 👤 Ensure target user exists and in sudo group
  ansible.builtin.user:
    name: "{{ ops_user }}"
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    state: present

- name: 🔓 Allow target user to use sudo without a password
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ ops_user }}"
    line: "{{ ops_user }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    state: present
    owner: root
    group: root
    mode: '0440'
    validate: "visudo -cf %s"

- name: 🔑 Copy SSH public key to authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ ops_user }}"
    key: "{{ lookup('file', ansible_user_public_key_file) }}"
  when: ansible_user_public_key_file is defined and ansible_user_public_key_file != ""

- name: 🔑 Ensure .ssh directory exists for ops user
  ansible.builtin.file:
    path: "/home/{{ ops_user }}/.ssh"
    state: directory
    owner: "{{ ops_user }}"
    group: "{{ ops_user }}"
    mode: '0700'
  when: ops_private_key is defined and ops_private_key != ""

- name: 🔑 Setup ops private key
  ansible.builtin.copy:
    dest: "/home/{{ ops_user }}/.ssh/id_rsa"
    content: "{{ ops_private_key }}"
    owner: "{{ ops_user }}"
    group: "{{ ops_user }}"
    mode: '0600'
  when: ops_private_key is defined and ops_private_key != ""
