- name: 🔐 Configure SSH hardening
  become: true
  block:
    - name: 🚫 Disable password authentication for SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        backup: true
      notify: Restart SSH
      become: true

    - name: ✅ Enable PubkeyAuthentication for SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        backup: true
      notify: Restart SSH
      become: true

    - name: 🔑 Ensure public key is present for target user
      ansible.builtin.authorized_key:
        user: "{{ target_user }}"
        key: "{{ lookup('file', ansible_user_public_key_file) }}"
        state: present
      become: true

    # DONT TOUCH THIS, WILL ENABLE LATER
    #    - name: 🚫 Disable root SSH login
    #      ansible.builtin.lineinfile:
    #        path: /etc/ssh/sshd_config
    #        regexp: '^PermitRootLogin'
    #        line: 'PermitRootLogin no'
    #        backup: true
    #      notify: Restart SSH