name: ☸️ K3s Cluster

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: 'Playbook to run'
        required: true
        default: 'site'
        type: choice
        options:
          - site
          - reset

jobs:
  k3s:
    uses: ./.github/.github/workflows/ansible.yml@main
    with:
      playbook: ansible/playbooks/k3s.yml
      inventory: ansible/inventories/k3s.py
      ansible_user: ops
      pre-build-hook: |
        echo "K3S_SERVERS=${{ vars.K3S_SERVERS }}" >> $GITHUB_ENV
        echo "K3S_AGENTS=${{ vars.K3S_AGENTS }}" >> $GITHUB_ENV
        echo "K3S_TOKEN=${{ secrets.asdasd }}" >> $GITHUB_ENV
        echo "playbook_name=${{ github.event.inputs.playbook }}" >> $GITHUB_ENV
        ansible-galaxy collection install -r ansible/requirements.yaml
    secrets:
      ssh_private_key: ${{ secrets.VPS_OPS_PRIVATE_KEY }}
      asdasd: asdas
