name: 🚀 Platform Foundation

on:
  push:
    branches:
      - main

jobs:
  platform-foundation:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: 🔑 Setup SSH Keys
        env:
          OPS_PRIVATE_KEY: ${{ secrets.VPS_OPS_PRIVATE_KEY }}
          ROOT_PRIVATE_KEY: ${{ secrets.VPS_ROOT_PRIVATE_KEY }}
          OPS_PUBLIC_KEY: ${{ secrets.VPS_OPS_PUBLIC_KEY }}
        run: |
          printf "%s" "$OPS_PRIVATE_KEY" > ops_private_key
          printf "%s" "$ROOT_PRIVATE_KEY" > root_private_key
          printf "%s" "$OPS_PUBLIC_KEY" > public_key
          
          chmod 600 ops_private_key root_private_key

      - name: ⚡ Run Ansible playbook
        env:
          VPS_IP_1: ${{ vars.VPS_IP_1 }}
          VPS_IP_2: ${{ vars.VPS_IP_2 }}
          VPS_IP_3: ${{ vars.VPS_IP_3 }}
        run: |
          make vps \
            OPS_KEY="${GITHUB_WORKSPACE}/ops_private_key" \
            ROOT_KEY="${GITHUB_WORKSPACE}/root_private_key" \
            PUB_KEY="${GITHUB_WORKSPACE}/public_key"