name: 🚀 Platform Foundation

on:
  workflow_dispatch:
    inputs:
      ansible_user:
        description: 'Ansible connection user'
        required: true
        default: 'ops'
        type: choice
        options:
          - ops
          - root

env:
  VPS_IP_1: ${{ vars.VPS_IP_1 }}
  VPS_IP_2: ${{ vars.VPS_IP_2 }}
  VPS_IP_3: ${{ vars.VPS_IP_3 }}

jobs:
  platform-foundation:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yaml -p ./collections

      - name: 🔑 Setup SSH Keys
        run: |
          printf "%s" "${{ secrets.VPS_OPS_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          
          ssh-keygen -y -f private_key > public_key
      
          if [ "${{ inputs.ansible_user }}" = "root" ]; then
            printf "%s" "${{ secrets.VPS_ROOT_PRIVATE_KEY }}" > private_key
          fi
          
          chmod 600 private_key

      - name: ⚡ Run Ansible playbook
        run: |
          make vps ANSIBLE_USER=${{ inputs.ansible_user }} ANSIBLE_USER_PRIVATE_KEY_FILE=private_key ANSIBLE_USER_PUBLIC_KEY_FILE=public_key
