name: 🐣 Provision VPS (Bootstrap)

on:
  workflow_dispatch:
    inputs:
      SSH_USER:
        description: 'User to connect with (root or ops)'
        required: true
        default: 'root'
        type: choice
        options:
          - ops
          - root

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v6

      - name: ⚙️ Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements.yaml
          pip-install: -r requirements.txt

      - name: 📦 Cache Virtual Environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: 🌌 Cache Ansible Collections
        uses: actions/cache@v4
        with:
          path: collections
          key: collections-${{ runner.os }}-${{ hashFiles('requirements.yaml') }}

      - name: 🔑 Setup SSH
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.VPS_ROOT_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          echo "${{ secrets.VPS_OPS_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_OPS_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub

      - name: ⚡ Run Bootstrap Playbook
        env:
          VPS_IP_1: ${{ vars.VPS_IP_1 }}
          VPS_IP_2: ${{ vars.VPS_IP_2 }}
          VPS_IP_3: ${{ vars.VPS_IP_3 }}
          ANSIBLE_USER: ${{ github.event.inputs.SSH_USER }}
          PUB_KEY_PATH: ~/.ssh/id_rsa.pub
        run: |
          make bootstrap
            
