name: 🛡️ Deploy WireGuard VPN

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/.github/workflows/ansible.yml@main
    with:
      playbook: ansible/playbooks/vpn.yml
      inventory: ansible/inventories/vpn.yaml
      ansible_user: ops
      pre-build-hook: |
        ansible-galaxy collection install -r ansible/requirements.yaml
    secrets: inherit